[package]
name = "open-company"
version = "0.0.0"
description = "Company Management Tools"
authors = ["ly3xqhl8g9"]
license = "DEL"
repository = "https://github.com/plurid/open-company"
edition = "2021"


[build-dependencies]
tauri-build = { version = "1.5", features = [] }


[dependencies]
diesel = { version ="2.1.4", features = ["sqlite", "returning_clauses_for_sqlite_3_35"] }
diesel_migrations = "2.1.0"
dirs = "5.0.1"
libsqlite3-sys = { version = "0.27.0", features = ["bundled"] }
pwhash = "1.0.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "1.5", features = [ "fs-read-dir", "fs-create-dir", "fs-write-file", "dialog-open", "dialog-save", "shell-open"] }


[features]
# this feature is used for production builds or when `devPath` points to the filesystem
# DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
